---
title: "R Notebook"
output: rmarkdown::github_document
always_allow_html: yes

---


```{r}
library(tidyverse)
library(lubridate)
library(plotly)
source('service/dbservice.R')
source('service/geoservice.R')
```
```{r}
df.history <- load.luftdaten.record.history.per.sensor()
df.history$date <- as_datetime(df.history$timestamp_gmt/1000)

df.history <- df.history %>% filter(date!=as.Date('2018-03-30'))

df.history.ratio <- df.history %>% spread(sensor_type_name,records,fill = 0) %>% mutate(ratio_bme280 = bme280/sds011*100, ratio_dht22 = dht22/sds011*100) %>%select(date,ratio_bme280,ratio_dht22) %>% gather(key,value,-date)

ggplot(df.history.ratio %>% filter(date>=as.Date('2017-01-01')),aes(date,value,fill=key))+ geom_line()

```

#plot per sensor

```{r}

p <-ggplot(df.history,aes(date,records))+ geom_line(aes(colour=sensor_type_name))
p
```
# plot per country
```{r}
df.history.country <- load.luftdaten.record.history.per.sensor.country()
df.history.country$date <- as_datetime(df.history.country$timestamp_gmt/1000)

df.history.country <- df.history.country %>% filter(date!=as.Date('2018-03-30')) %>% filter(!is.na(location_country))
df.history.country$day.of.month <- day(df.history.country$date)

p <-ggplot(df.history.country %>% filter(sensor_type_name %in% c('sds011') & day.of.month==1 & location_country %in% c('DE','BG','FR')),aes(date,records,fill=location_country))+ geom_bar(stat="identity",position = 'dodge')
p
```
# plot country split
```{r}
groupy <- df.history.country %>% filter(date==as.Date('2019-06-01') & sensor_type_name=='bme280') %>% top_n(10,records)

ggplot(groupy,aes(reorder(location_country,-records),records, fill=location_country))+geom_bar(stat="identity")
```
## ratio bme/sds011 per location
```{r}
df.sensors <- load.luftdaten.sensors()

groupy <- df.sensors %>% group_by(location_id,sensor_type_name) %>% summarise(total = n()) %>% spread(sensor_type_name,total)
df.equipement.per.location <-as.data.frame((1-colMeans(is.na(groupy)))*100)
colnames(df.equipement.per.location)<-c('percent_equiped')
df.equipement.per.location <- df.equipement.per.location %>% rownames_to_column('sensor_type_name')

ggplot(df.equipement.per.location ,aes(reorder(sensor_type_name,-percent_equiped),percent_equiped))+geom_bar(stat="identity")+
  theme(axis.text.x = element_text(angle = 90))


```

## get location with both BME280 AND DHT22 for which we have data
```{r}
locationsDHT22_AND_BME280 <-groupy %>% filter(BME280>0 & DHT22>0) %>% pull(location_id)

sensors.with.data <- load.luftdaten.sensors.with.data()%>% filter(location_id %in% locationsDHT22_AND_BME280)
locationWithDataWithBME280_and_DHT22 <- sensors.with.data %>% filter(sensor_type_id==9) %>% pull(location_id)

sensors_for_those_locations <-sensors.with.data %>% filter(location_id %in% locationWithDataWithBME280_and_DHT22) %>% pull(sensor_id)

df<- prepare.data('None',sensors_for_those_locations)
df <- merge(df,df.sensors %>% select(location_id,sensor_id),by='sensor_id')


ggplot(df %>% filter( variable=='humidity'),aes(datetime,value,color=sensor_id))+ geom_line()+facet_wrap(.~location_id,nrow = 3)
ggplot(df %>% filter( variable=='humidity'),aes(value,color=sensor_id))+ geom_histogram()+facet_wrap(.~sensor_id,nrow = 3)
```
```{r}

```

